from enum import Enum, auto

class Indices(Enum):
    ATIVO = "ativo"
    CAMBIO = "cambio"
    DATA = "data"
    PRAZO = "prazo"
    PRECO = "preco"
    VALOR = "valor"

class AcoesBr(Enum):
    IBOVESPA = "IBOV"
    AMBEV = "AMBV3"
    BANCO_DO_BRASIL = "BBAS3"
    B3 = "B3SA3"
    BRADESCO = "BBDC4"
    BRASKEM = "BRKM5"
    BRF = "BRFS3"
    CMIG = "CMIG4"
    CSN = "CSNA3"
    EMBRAER = "EMBR3"
    GERDAU = "GOAU4"
    ITAU = "ITUB4"
    MAGAZINE_LUIZA = "MGLU3"
    MARFRIG = "MRFG3"
    LOJAS_RENNER = "LREN3"
    PETROBRAS = "PETR4"
    PRIO = "PRIO3"
    SUZANO = "SUZB3"
    VALE = "VALE3"
    CASAS_BAHIA = "BHIA3"

class AcoesUs(Enum):
    ALCOA = "AA"
    AMAZON = "AMZN"
    APPLE = "AAPL"
    ATnT = "T"
    BANK_OF_AMERICA = "BAC"
    GOOGLE = "GOOGL"
    INTEL = "INTC"
    MICROSOFT = "MSFT"
    FORD_MOTORS = "F"
    TESLA = "TSLA"

class Opcoes(Enum):
    OPCAO_1 = "Opção 1"
    OPCAO_2 = "Opção 2"
    OPCAO_3 = "Opção 3"
    OPCAO_4 = "Opção 4"
    OPCAO_5 = "Opção 5"
    OPCAO_6 = "Opção 6"
    OPCAO_7 = "Opção 7"
    OPCAO_8 = "Opção 8"
    OPCAO_9 = "Opção 9"
    OPCAO_10 = "Opção 10"
    OPCAO_11 = "Opção 11"
    OPCAO_12 = "Opção 12"
    OPCAO_13 = "Opção 13"
    OPCAO_14 = "Opção 14"

class Titulos(Enum):
    TITULO_1 = "Título 1"
    TITULO_2 = "Título 2"
    TITULO_3 = "Título 3"
    TITULO_4 = "Título 4"
    TITULO_5 = "Título 5"
    TITULO_6 = "Título 6"
    TITULO_7 = "Título 7"
    TITULO_8 = "Título 8"
    TITULO_9 = "Título 9"
    TITULO_10 = "Título 10"

